# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='考试名称')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('grade', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Exam', verbose_name='考试')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('season', models.IntegerField(choices=[(0, '上学期'), (1, '下学期')], verbose_name='学期')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('name', models.CharField(max_length=6)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[\\d|-]+', message='号码格式错误')])),
                ('teaching_grade', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crew.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]\\d+', '学号格式错误')], verbose_name='学号')),
                ('exam_id', models.CharField(blank=True, max_length=20, verbose_name='考号')),
                ('national_id', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=6, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('school', models.CharField(choices=[('BB', '博白(0646)'), ('BX', '博学(0657)')], max_length=2, verbose_name='学校')),
                ('prop', models.CharField(choices=[('Y', '应届生'), ('W', '往届生')], max_length=1, verbose_name='是否应届')),
                ('grade_idx', models.SmallIntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], verbose_name='年级')),
                ('class_idx', models.SmallIntegerField(verbose_name='班号')),
                ('category', models.CharField(choices=[('W', '文科'), ('L', '理科'), ('U', '未分科')], max_length=1, verbose_name='文理状态')),
                ('enroll_year', models.IntegerField(verbose_name='入学年份(四位)')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='科目')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='teaching_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Subject'),
        ),
        migrations.AddField(
            model_name='record',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Semester', verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Subject', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='crew.Subject', verbose_name='包含科目'),
        ),
    ]
