# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_id_alt',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
