# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prop',
            field=models.CharField(choices=[('Y', '应届生'), ('W', '往届生')], max_length=1, verbose_name='学生类别'),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('subject', 'student', 'semester', 'exam')]),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('year', 'season')]),
        ),
    ]
