# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_auto_20160712_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Exam')),
                ('default_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Semester')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='belong_art',
            field=models.BooleanField(default=False, verbose_name='文科是否统计'),
        ),
        migrations.AddField(
            model_name='subject',
            name='belong_science',
            field=models.BooleanField(default=False, verbose_name='理科是否统计'),
        ),
        migrations.AddField(
            model_name='subject',
            name='belong_universal',
            field=models.BooleanField(default=False, verbose_name='不分科是否统计'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='满分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='科目'),
        ),
    ]
