# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 05:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_auto_20160706_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='考试名称')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='成绩')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('season', models.IntegerField(choices=[(0, '上学期'), (0, '下学期')], verbose_name='学期')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('W', '文科'), ('L', '理科'), ('U', '未分科')], max_length=1, verbose_name='文理状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_idx',
            field=models.SmallIntegerField(verbose_name='班号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_year',
            field=models.IntegerField(verbose_name='入学年份(四位)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(max_length=10, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='考号1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam_id_alt',
            field=models.CharField(blank=True, max_length=10, verbose_name='考号2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_idx',
            field=models.SmallIntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hukou_is_agri',
            field=models.BooleanField(choices=[(0, '非农业户口'), (1, '农业户口')], verbose_name='户口'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=6, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=18, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='native_place',
            field=models.CharField(max_length=30, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[\\d|-]+', message='号码格式错误')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='political_status',
            field=models.CharField(choices=[('DY', '中共党员'), ('TY', '共青团员'), ('QZ', '群众')], max_length=2, verbose_name='政治面貌'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prop',
            field=models.CharField(choices=[('Y', '应届生'), ('W', '往届生')], max_length=1, verbose_name='是否应届'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('BB', '博白(0646)'), ('BX', '博学(0657)')], max_length=2, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]\\d+', '学号格式错误')], verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=10, verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='record',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Semester', verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Subject', verbose_name='科目'),
        ),
    ]
