# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_auto_20160710_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='crew.Subject'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='season',
            field=models.IntegerField(choices=[(0, '上学期'), (1, '下学期')], verbose_name='学期'),
        ),
    ]
