# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 16:55
from __future__ import unicode_literals

import crew.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_auto_20160714_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='segments',
            field=crew.models.SegmentsField(default=[], max_length=1024, verbose_name='分数段'),
        ),
    ]
