# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 17:42
from __future__ import unicode_literals

import crew.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_subject_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='art_segments',
            field=crew.models.SegmentsField(default='', max_length=1024, verbose_name='文科分数段'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='science_segments',
            field=crew.models.SegmentsField(default='', max_length=1024, verbose_name='理科分数段'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='universal_segments',
            field=crew.models.SegmentsField(default='', max_length=1024, verbose_name='不分科分数段'),
            preserve_default=False,
        ),
    ]
