# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 09:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_auto_20160714_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='excellent_ratio',
            field=models.FloatField(default=0.9, validators=[django.core.validators.MaxValueValidator(1, '比例不能超过1'), django.core.validators.MinValueValidator(0, '比例不能小于0')], verbose_name='优比例'),
        ),
        migrations.AddField(
            model_name='subject',
            name='good_ratio',
            field=models.FloatField(default=0.8, validators=[django.core.validators.MaxValueValidator(1, '比例不能超过1'), django.core.validators.MinValueValidator(0, '比例不能小于0')], verbose_name='良比例'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_ratio',
            field=models.FloatField(default=0.6, validators=[django.core.validators.MaxValueValidator(1, '比例不能超过1'), django.core.validators.MinValueValidator(0, '比例不能小于0')], verbose_name='及格比例'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='segments',
            field=models.CommaSeparatedIntegerField(default=[], max_length=1024, verbose_name='分数段'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='art_segments',
            field=models.CommaSeparatedIntegerField(max_length=1024, verbose_name='文科分数段'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='science_segments',
            field=models.CommaSeparatedIntegerField(max_length=1024, verbose_name='理科分数段'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='universal_segments',
            field=models.CommaSeparatedIntegerField(max_length=1024, verbose_name='不分科分数段'),
        ),
    ]
