# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_auto_20160716_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('BB', '博白(0646)'), ('BX', '博学(0657)')], max_length=2, verbose_name='学校')),
                ('grade_idx', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], verbose_name='年级')),
                ('class_idx', models.IntegerField(verbose_name='班级')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Staff')),
            ],
            options={
                'verbose_name': '任课教师/班主任',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('BB', '博白(0646)'), ('BX', '博学(0657)')], max_length=2, verbose_name='学校')),
                ('grade_idx', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], verbose_name='年级')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Staff')),
            ],
            options={
                'verbose_name': '教研组长',
            },
        ),
        migrations.CreateModel(
            name='SubjectLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('BB', '博白(0646)'), ('BX', '博学(0657)')], max_length=2, verbose_name='学校')),
                ('grade_idx', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], verbose_name='年级')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crew.Staff')),
            ],
            options={
                'verbose_name': '备课组长',
            },
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together=set([('school', 'grade_idx', 'class_idx', 'subject')]),
        ),
    ]
