# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0007_auto_20160717_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classteacher',
            options={'verbose_name': '任课教师/班主任', 'verbose_name_plural': '任课教师/班主任'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': '教研组长', 'verbose_name_plural': '教研组长'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '职工', 'verbose_name_plural': '职工'},
        ),
        migrations.AlterModelOptions(
            name='subjectleader',
            options={'verbose_name': '备课组长', 'verbose_name_plural': '备课组长'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='teaching_grade',
        ),
    ]
