# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0009_auto_20160717_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.IntegerField(choices=[(1, '高一年级'), (3, '高二年级'), (3, '高三年级'), (-1, '初一年级'), (-2, '初二年级'), (-3, '初三年级')], primary_key=True, serialize=False)),
                ('level_a_rank', models.IntegerField()),
                ('level_b_rank', models.IntegerField()),
            ],
        ),
    ]
